### ISSUE TITLE
Code review 

### ISSUE THREAD

**Issue by MahmoudMabrok** [hamza94max/To-Do-App#4]
https://github.com/hamza94max/To-Do-App/blob/5d3597891fabba485c736752632125317afe54de/app/src/main/java/com/hamza/todoapp/ui/ToDoFragment/ToDoFragment.kt#L30

Use single viewmodel for current screen

**Comment by hamza94max** [comment]
> https://github.com/hamza94max/To-Do-App/blob/5d3597891fabba485c736752632125317afe54de/app/src/main/java/com/hamza/todoapp/ui/ToDoFragment/ToDoFragment.kt#L30
> 
> Use single viewmodel for current screen

But different business, Single Responsibility in SOLID ?

**Comment by hamza94max** [comment]
The code is totally refactored, you can see the pull request if you have time 

Thanks
